[versions]
androidDateTimeFormatters = "2.2.0"
androidPluginGradle = "8.5.0"
androidx-activity = "1.9.0"
androidx-compose = "1.6.8"
androidx-compose-compiler = "1.5.14"
androidx-compose-wear = "1.3.1"
androidx-lifecycle = "2.8.2"
androidx-room = "2.6.1"
androidx-wear = "1.3.0"
dagger = "2.51.1"
kotlin-coroutines = "1.8.1"
logcat = "0.1"
kotlin = "2.0.0"
playServices-wearable = "18.2.0"
versionsPlugin-gradle = "0.51.0"
wire = "4.9.9"

[libraries]
androidDateTimeFormatters = { module = "dev.drewhamilton.androidtime:datetimeformatters", version.ref = "androidDateTimeFormatters" }
androidPluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidPluginGradle" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-wear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-compose-wear" }
androidx-compose-wear-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-compose-wear" }
androidx-compose-wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-compose-wear" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidx-wear" }
dagger-hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
dagger-hilt-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
playServices-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServices-wearable" }
versionsPlugin-gradle = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsPlugin-gradle" }
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-pluginGradle = { module = "com.squareup.wire:wire-gradle-plugin", version.ref = "wire" }

[plugins]
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
